plugins {
    id 'fabric-loom' version '1.9.2' apply(false)
    id 'maven-publish'
}

group 'top.gregtao.xibao'

allprojects {
    apply plugin: 'java'

    sourceSets {
        main {
            resources {
                srcDir 'resources'
            }
        }
    }
}

subprojects {
    sourceSets {
        main {
            resources {
                srcDirs += project(':').sourceSets.main.resources.srcDirs // 引用父级项目的资源文件夹
            }
        }
    }

    apply plugin: 'fabric-loom'

    archivesBaseName = project(':').archives_base_name
    setVersion(project.mod_version)

    repositories {
    }

    dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
        modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
        modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    }

    processResources {
        inputs.property "version", project.version

        filesMatching("fabric.mod.json") {
            expand "version": project.version
        }
    }

    java {
    }

    jar {
        from("LICENSE") {
            rename { "${it}_${project.archivesBaseName}"}
        }
    }
}

project(":Fabric-1.21.4") {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}

project(":Fabric-1.21.1") {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}

project(":Fabric-1.20.6") {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}

project(":Fabric-1.20.4") {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }
}

project(":Fabric-1.20.1") {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }
}

project(":Fabric-1.20") {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }
}

project(":Fabric-1.19.4") {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }
}

project(":Fabric-1.19.3") {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }
}

project(":Fabric-1.19") {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }
}

project(":Fabric-1.18.2") {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }
}

project(":Fabric-1.17.1") {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 16
    }
}

project(":Fabric-1.16.5") {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 8
    }
}