name: Build
on:
  push:
    branches: [Fabric]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Use Gradle build action
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: xibao-build
          path: |
            Fabric-*/build/libs/XibaoPlusPlus-*-*-mc*.jar
            !Fabric-*/build/libs/XibaoPlusPlus-*-*-mc*-*.jar